import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  nl: {
    nav: {
      home: 'Home',
      finder: 'Woning Zoeker',
      rentBuy: 'Huren vs Kopen',
      taxes: 'Belastingen & Kosten',
      neighborhood: 'Buurtanalyse',
      history: 'Prijsgeschiedenis',
      cheapest: 'Goedkoopste Nabij',
      expensive: 'Duurste Nabij',
    },
    hero: {
      title: 'Slimme Woninganalyse voor Nederland',
      subtitle: 'Analyseer woningen, buurten en vastgoeddata met betrouwbare Nederlandse bronnen',
      placeholder: 'Voer een postcode of Funda URL in...',
      cta: 'Analyseer Nu',
    },
    tools: {
      finder: 'Woning Zoeker',
      finderDesc: 'Analyseer elke woning op Funda',
      rentBuy: 'Huren vs Kopen',
      rentBuyDesc: 'Bereken wat financieel gunstiger is',
      taxes: 'Belastingen & Kosten',
      taxesDesc: 'Overzicht van alle kosten bij aankoop',
      neighborhood: 'Buurtanalyse',
      neighborhoodDesc: 'Score voor scholen, winkels, veiligheid',
      history: 'Prijsgeschiedenis',
      historyDesc: 'Historische prijsontwikkeling per locatie',
      cheapest: 'Goedkoopste Nabij',
      cheapestDesc: 'Top 10 goedkoopste woningen in de buurt',
      expensive: 'Duurste Nabij',
      expensiveDesc: 'Top 10 duurste woningen in de buurt',
    },
    trust: {
      title: 'Betrouwbare Databronnen',
      cbs: 'CBS Statistieken',
      bag: 'BAG Kadaster',
      funda: 'Funda Listings',
      osm: 'OpenStreetMap',
    },
    footer: {
      disclaimer: 'Huis Analist biedt informatieve analyses op basis van publiek beschikbare data. Raadpleeg altijd een financieel adviseur voor persoonlijk advies.',
      sources: 'Databronnen: CBS, BAG/Kadaster, Funda, OpenStreetMap',
    },
    common: {
      analyze: 'Analyseer',
      loading: 'Laden...',
      error: 'Er is een fout opgetreden',
      postalCode: 'Postcode',
      address: 'Adres',
      price: 'Prijs',
      area: 'Oppervlakte',
      pricePerM2: 'Prijs per m²',
      aiExplanation: 'AI Uitleg',
      generateExplanation: 'Genereer Uitleg',
      source: 'Bron',
      back: '← Terug',
    },
    rentBuyPage: {
      title: 'Huren vs Kopen Calculator',
      housePrice: 'Aankoopprijs woning',
      mortgageRate: 'Hypotheekrente (%)',
      rentPrice: 'Maandhuur',
      years: 'Jaren dat u er woont',
      recommendation: 'Aanbeveling',
      totalCostBuy: 'Totale kosten kopen',
      totalCostRent: 'Totale kosten huren',
      monthlyMortgage: 'Maandelijkse hypotheek',
      cheaper: 'goedkoper',
      buyRecommended: 'Kopen is financieel voordeliger',
      rentRecommended: 'Huren is financieel voordeliger',
    },
    taxesPage: {
      title: 'Belastingen & Kosten Calculator',
      housePrice: 'Aankoopprijs',
      municipality: 'Gemeente',
      transferTax: 'Overdrachtsbelasting',
      propertyTax: 'OZB (per jaar)',
      notaryCosts: 'Notariskosten',
      mortgageCosts: 'Hypotheekkosten',
      total: 'Totaal eenmalige kosten',
      annualCosts: 'Jaarlijkse kosten',
    },
    neighborhoodPage: {
      title: 'Buurtanalyse',
      schools: 'Scholen',
      shops: 'Winkels',
      transport: 'OV',
      safety: 'Veiligheid',
      greenSpace: 'Groenvoorziening',
      overall: 'Totaalscore',
    },
    historyPage: {
      title: 'Prijsgeschiedenis',
      averagePrice: 'Gemiddelde Prijs',
      transactions: 'Transacties',
    },
    nearbyPage: {
      cheapestTitle: 'Goedkoopste Woningen Nabij',
      expensiveTitle: 'Duurste Woningen Nabij',
      sortBy: 'Sorteren op',
      bedrooms: 'Slaapkamers',
      type: 'Type',
      sqm: 'm²',
    },
  },
  en: {
    nav: {
      home: 'Home',
      finder: 'Housing Finder',
      rentBuy: 'Rent vs Buy',
      taxes: 'Taxes & Fees',
      neighborhood: 'Neighborhood',
      history: 'Price History',
      cheapest: 'Cheapest Nearby',
      expensive: 'Most Expensive',
    },
    hero: {
      title: 'Smart Housing Analysis for the Netherlands',
      subtitle: 'Analyze properties, neighborhoods and real estate data with reliable Dutch sources',
      placeholder: 'Enter a postal code or Funda URL...',
      cta: 'Analyze Now',
    },
    tools: {
      finder: 'Housing Finder',
      finderDesc: 'Analyze any property on Funda',
      rentBuy: 'Rent vs Buy',
      rentBuyDesc: 'Calculate what is financially better',
      taxes: 'Taxes & Fees',
      taxesDesc: 'Overview of all purchase costs',
      neighborhood: 'Neighborhood Score',
      neighborhoodDesc: 'Score for schools, shops, safety',
      history: 'Price History',
      historyDesc: 'Historical price development by location',
      cheapest: 'Cheapest Nearby',
      cheapestDesc: 'Top 10 cheapest properties nearby',
      expensive: 'Most Expensive',
      expensiveDesc: 'Top 10 most expensive properties nearby',
    },
    trust: {
      title: 'Reliable Data Sources',
      cbs: 'CBS Statistics',
      bag: 'BAG Cadastre',
      funda: 'Funda Listings',
      osm: 'OpenStreetMap',
    },
    footer: {
      disclaimer: 'Huis Analist provides informational analyses based on publicly available data. Always consult a financial advisor for personal advice.',
      sources: 'Data sources: CBS, BAG/Cadastre, Funda, OpenStreetMap',
    },
    common: {
      analyze: 'Analyze',
      loading: 'Loading...',
      error: 'An error occurred',
      postalCode: 'Postal Code',
      address: 'Address',
      price: 'Price',
      area: 'Area',
      pricePerM2: 'Price per m²',
      aiExplanation: 'AI Explanation',
      generateExplanation: 'Generate Explanation',
      source: 'Source',
      back: '← Back',
    },
    rentBuyPage: {
      title: 'Rent vs Buy Calculator',
      housePrice: 'House price',
      mortgageRate: 'Mortgage rate (%)',
      rentPrice: 'Monthly rent',
      years: 'Years you will live there',
      recommendation: 'Recommendation',
      totalCostBuy: 'Total cost buying',
      totalCostRent: 'Total cost renting',
      monthlyMortgage: 'Monthly mortgage',
      cheaper: 'cheaper',
      buyRecommended: 'Buying is financially better',
      rentRecommended: 'Renting is financially better',
    },
    taxesPage: {
      title: 'Property Taxes & Fees Calculator',
      housePrice: 'Purchase price',
      municipality: 'Municipality',
      transferTax: 'Transfer tax',
      propertyTax: 'Property tax (per year)',
      notaryCosts: 'Notary costs',
      mortgageCosts: 'Mortgage costs',
      total: 'Total one-time costs',
      annualCosts: 'Annual costs',
    },
    neighborhoodPage: {
      title: 'Neighborhood Score Analyzer',
      schools: 'Schools',
      shops: 'Shops',
      transport: 'Public Transport',
      safety: 'Safety',
      greenSpace: 'Green Space',
      overall: 'Overall Score',
    },
    historyPage: {
      title: 'Price History Tracker',
      averagePrice: 'Average Price',
      transactions: 'Transactions',
    },
    nearbyPage: {
      cheapestTitle: 'Cheapest Properties Nearby',
      expensiveTitle: 'Most Expensive Properties Nearby',
      sortBy: 'Sort by',
      bedrooms: 'Bedrooms',
      type: 'Type',
      sqm: 'm²',
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('nl');
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
